### ISSUE TITLE
Unit Tests of utility functions

### ISSUE THREAD

**Issue by cowglow** [compose-us/wichteln#3]
**Description**
The utility functions don't have tests. Add the Jest dependency and add additional configurations to be able to create `.spec.ts` files.

Simply create the tests for each of the utility functions and which ever edge cases you can find.

Also add Script for executing test suite.

**Links/References**
https://jestjs.io/docs/getting-started

**Tasks**

- [ ] Add dependency
- [ ] Configure Jest for project
- [ ] Add Unit tests for utility funcs
- [ ] Add Script command to `package.json`

**Additional Context**
